name: Run TCP-UDP Video Project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Run main.py to create output report
        run: |
          python main.py
      - name: Upload output artifact
        uses: actions/upload-artifact@v4
        with:
          name: project-report
          path: output.txt
